Model Training
Import Data and Required Packages
Importing Pandas, Numpy, Matplotlib, Seaborn and Warings Library.

In [6]:
!pip install scikit-learn
!pip install catboost xgboost

Requirement already satisfied: scikit-learn in c:\projects\mlproject\venv\lib\site-packages (1.7.0)
Requirement already satisfied: numpy>=1.22.0 in c:\projects\mlproject\venv\lib\site-packages (from scikit-learn) (2.3.1)
Requirement already satisfied: scipy>=1.8.0 in c:\projects\mlproject\venv\lib\site-packages (from scikit-learn) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\projects\mlproject\venv\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\projects\mlproject\venv\lib\site-packages (from scikit-learn) (3.6.0)
Collecting catboost
  Downloading catboost-1.2.8-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting xgboost
  Downloading xgboost-3.0.2-py3-none-win_amd64.whl.metadata (2.1 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\projects\mlproject\venv\lib\site-packages (from catboost) (3.10.3)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\projects\mlproject\venv\lib\site-packages (from catboost) (2.3.1)
Requirement already satisfied: pandas>=0.24 in c:\projects\mlproject\venv\lib\site-packages (from catboost) (2.3.0)
Requirement already satisfied: scipy in c:\projects\mlproject\venv\lib\site-packages (from catboost) (1.16.0)
Collecting plotly (from catboost)
  Downloading plotly-6.2.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: six in c:\users\jaysw\appdata\roaming\python\python313\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jaysw\appdata\roaming\python\python313\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\projects\mlproject\venv\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\projects\mlproject\venv\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\projects\mlproject\venv\lib\site-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\projects\mlproject\venv\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\projects\mlproject\venv\lib\site-packages (from matplotlib->catboost) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\projects\mlproject\venv\lib\site-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\jaysw\appdata\roaming\python\python313\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\projects\mlproject\venv\lib\site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\projects\mlproject\venv\lib\site-packages (from matplotlib->catboost) (3.2.3)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-1.45.0-py3-none-any.whl.metadata (11 kB)
Downloading catboost-1.2.8-cp313-cp313-win_amd64.whl (102.4 MB)
   ---------------------------------------- 0.0/102.4 MB ? eta -:--:--
   ------ --------------------------------- 16.3/102.4 MB 99.8 MB/s eta 0:00:01
   ------------ -------------------------- 32.5/102.4 MB 100.6 MB/s eta 0:00:01
   ---------------- ----------------------- 42.2/102.4 MB 72.8 MB/s eta 0:00:01
   ------------------------- -------------- 65.8/102.4 MB 84.2 MB/s eta 0:00:01
   ----------------------------------- ---- 90.7/102.4 MB 91.2 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 93.6 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 93.6 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 93.6 MB/s eta 0:00:01
   --------------------------------------- 102.4/102.4 MB 60.6 MB/s eta 0:00:00
Downloading xgboost-3.0.2-py3-none-win_amd64.whl (150.0 MB)
   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ------ -------------------------------- 25.2/150.0 MB 118.2 MB/s eta 0:00:02
   ----------- --------------------------- 45.6/150.0 MB 106.6 MB/s eta 0:00:01
   --------------- ------------------------ 58.7/150.0 MB 91.5 MB/s eta 0:00:01
   ------------------ --------------------- 70.3/150.0 MB 83.1 MB/s eta 0:00:01
   ---------------------- ----------------- 82.6/150.0 MB 77.8 MB/s eta 0:00:01
   ------------------------- -------------- 94.1/150.0 MB 74.7 MB/s eta 0:00:01
   --------------------------- ----------- 107.0/150.0 MB 72.5 MB/s eta 0:00:01
   ------------------------------- ------- 119.3/150.0 MB 71.1 MB/s eta 0:00:01
   ---------------------------------- ---- 131.6/150.0 MB 70.0 MB/s eta 0:00:01
   ------------------------------------- - 144.4/150.0 MB 69.1 MB/s eta 0:00:01
   --------------------------------------  149.9/150.0 MB 68.4 MB/s eta 0:00:01
   --------------------------------------  149.9/150.0 MB 68.4 MB/s eta 0:00:01
   --------------------------------------  149.9/150.0 MB 68.4 MB/s eta 0:00:01
   --------------------------------------  149.9/150.0 MB 68.4 MB/s eta 0:00:01
   --------------------------------------- 150.0/150.0 MB 49.8 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading plotly-6.2.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------  9.4/9.6 MB 54.6 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 32.8 MB/s eta 0:00:00
Downloading narwhals-1.45.0-py3-none-any.whl (371 kB)
Installing collected packages: narwhals, graphviz, xgboost, plotly, catboost

   ---------------------------------------- 0/5 [narwhals]
   ---------------------------------------- 0/5 [narwhals]
   ---------------------------------------- 0/5 [narwhals]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ---------------- ----------------------- 2/5 [xgboost]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   ------------------------ --------------- 3/5 [plotly]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   -------------------------------- ------- 4/5 [catboost]
   ---------------------------------------- 5/5 [catboost]

Successfully installed catboost-1.2.8 graphviz-0.21 narwhals-1.45.0 plotly-6.2.0 xgboost-3.0.2

In [ ]:

# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
# No code needed here, you can simply remove the $SELECTION_PLACEHOLDER$ and the empty line.
from sklearn.linear_model import Ridge,Lasso
from sklearn.metrics import mean_absolute_error
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

Import the CSV Data as Pandas DataFrame

In [10]:
df = pd.read_csv('C:/projects/mlproject/notebook/data/stud.csv')

Show Top 5 Records

In [11]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

Preparing X and Y variables

In [12]:
X = df.drop(columns=['math_score'],axis=1)
X.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [13]:
print("Categories in 'gender' variable:     ",end=" " )
print(df['gender'].unique())

print("Categories in 'race_ethnicity' variable:  ",end=" ")
print(df['race_ethnicity'].unique())

print("Categories in'parental level of education' variable:",end=" " )
print(df['parental_level_of_education'].unique())

print("Categories in 'lunch' variable:     ",end=" " )
print(df['lunch'].unique())

print("Categories in 'test preparation course' variable:     ",end=" " )
print(df['test_preparation_course'].unique())

Categories in 'gender' variable:      ['female' 'male']
Categories in 'race_ethnicity' variable:   ['group B' 'group C' 'group A' 'group D' 'group E']
Categories in'parental level of education' variable: ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
Categories in 'lunch' variable:      ['standard' 'free/reduced']
Categories in 'test preparation course' variable:      ['none' 'completed']

In [14]:
y = df['math_score']

In [15]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math_score, Length: 1000, dtype: int64

In [16]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
         ("StandardScaler", numeric_transformer, num_features),        
    ]
)

In [17]:
X = preprocessor.fit_transform(X)
X.shape

(1000, 19)

In [18]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((800, 19), (200, 19))

Create an Evaluate Function to give all metrics after model Training

In [19]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "CatBoosting Regressor": CatBoostRegressor(verbose=False),
    "AdaBoost Regressor": AdaBoostRegressor()
}
model_list = []
r2_list =[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 5.3231
- Mean Absolute Error: 4.2667
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3940
- Mean Absolute Error: 4.2148
- R2 Score: 0.8804
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 6.5938
- Mean Absolute Error: 5.2063
- R2 Score: 0.8071
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.5197
- Mean Absolute Error: 5.1579
- R2 Score: 0.8253
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 5.3233
- Mean Absolute Error: 4.2650
- R2 Score: 0.8743
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3904
- Mean Absolute Error: 4.2111
- R2 Score: 0.8806
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 5.7077
- Mean Absolute Error: 4.5167
- R2 Score: 0.8555
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.2530
- Mean Absolute Error: 5.6210
- R2 Score: 0.7838
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.2795
- Mean Absolute Error: 0.0187
- R2 Score: 0.9997
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 8.2789
- Mean Absolute Error: 6.6200
- R2 Score: 0.7183
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 2.2940
- Mean Absolute Error: 1.8251
- R2 Score: 0.9767
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.9648
- Mean Absolute Error: 4.6380
- R2 Score: 0.8538
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 1.0073
- Mean Absolute Error: 0.6875
- R2 Score: 0.9955
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.4733
- Mean Absolute Error: 5.0577
- R2 Score: 0.8278
===================================


CatBoosting Regressor
Model performance for Training set
- Root Mean Squared Error: 3.0427
- Mean Absolute Error: 2.4054
- R2 Score: 0.9589
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.0086
- Mean Absolute Error: 4.6125
- R2 Score: 0.8516
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 5.8205
- Mean Absolute Error: 4.7722
- R2 Score: 0.8497
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.9609
- Mean Absolute Error: 4.6633
- R2 Score: 0.8540
===================================